### ISSUE TITLE
Matrix.applyToContext not updating the canvas state

### ISSUE THREAD

**Issue by jchayan** [epistemex/transformation-matrix-js#1]
Hi, first of all thank you for this small library. It has various useful things I want to make use of. I'm trying to setup a simple working demo based on the examples provided and the documentation given but it's not working.

Basically I have drawn an image in a canvas and I want to perform some operations (like transform / rotate / shear / etc). I'm creating a matrix based on my canvas context, applying the operations and then calling "applyToContext" in order to update the canvas.

Here's my snippet:

```
var onDOMContentLoaded = function (event) {
    var canvas, context, image;

    canvas = document.getElementById('canvas');
    context = canvas.getContext('2d');
    image = new Image();

    image.addEventListener('load', function (event) {
        var width, height;

        width = image.naturalWidth;
        height = image.naturalHeight;

        canvas.width = width;
        canvas.height = height;

        context.drawImage(image, 0, 0, canvas.width, canvas.height);

        var matrix = new Matrix(context);

        matrix.rotateDeg(45).translate(100, 200);
        matrix.applyToContext(context);
    });

    image.src = './image.png';
};

document.addEventListener('DOMContentLoaded', onDOMContentLoaded); 
```

It is most likely that I'm doing something wrong, or is this a bug?

Thank you in advance.

**Comment by epistemex** [comment]
Transforms on context must always be applied *before* drawing. In this case the transforms are applied after the image has already been drawn, i.e. nothing will happen.

Try this order instead (you don't need to use `applyToContext()` at all btw, since the context is automatically synced when given as argument to the constructor - the method is meant for contexts that are not synced or in scenario where you want to sync several contexts at once):

    var matrix = new Matrix(context);               // context given here will be synced automatically
    matrix.rotateDeg(45).translate(100, 200);   // apply before drawing to canvas
    //matrix.applyToContext(context);   not needed since new Matrix will sync it automatically

    context.drawImage(image, 0, 0, canvas.width, canvas.height);
