### ISSUE TITLE
Code improvements by our temporary fork 

### ISSUE THREAD

**Issue by redaxmedia** [epistemex/transformation-matrix-js#2]
Hello,

after you deleted this repo I had to continue your Matrix library, because it is a dependency of our Pageflip project at work. However, I hope you will **never ever delete your account again** and continue the maintenance. Please consider to merge my code improvements.

1. Huge performance boost using the Matrix3d for dragging / translate on mobiles:
https://github.com/marktjagd/transformation-matrix-js/blob/master/src/matrix.js#L682-L689

2. Simplified toJSON:
https://github.com/marktjagd/transformation-matrix-js/blob/master/src/matrix.js#L691-L697

3. Please introduce a dist folder with the latest minified version:
https://github.com/marktjagd/transformation-matrix-js/tree/master/dist

Let me know what you think.

Best regards
Henry

**Comment by epistemex** [comment]
Hi Henry,

yeah, there are sometimes rough times.. Thank you for your concern though; I will keep the account up this time. :)

The changes looks straight forward and I will accept the toCSS3D method. The simplified version of toJSON() using stringify is noticeable slower as expected (~250-1350x<sup>1</sup> depending on browser mood). toJSON() is perhaps not used for performance critical parts in general, but I will prefer to keep the existing implementation for now even with the extra few bytes. I will need to think about 3) as this would break my scripted setup and scopes.

Let me in a any case merge/implement the change and update credits etc. Thanks again!

<sup>1</sup>) Just for reference:
![jsperf snapshot](http://i.imgur.com/ApFOxzf.png)

Quick-n-dirty non-accurate test which still provides a good pointer in this case:
https://jsperf.com/matrix-test-json-vs-string

**Comment by redaxmedia** [comment]
Thank you very much, you can add Credits for Marktjagd, the company where I developed the code improvements. Looking forward to switch back to your repo using bower or npm.
