### ISSUE TITLE
Matrix.from unexpected behavior

### ISSUE THREAD

**Issue by krabbypattified** [epistemex/transformation-matrix-js#3]
`Matrix.from(el)` when `el`'s computed matrix is `'matrix(1, 0, 0, 1, -781, 0)'` or `none` it returns:

`Matrix {d: NaN, a: NaN, f: NaN,.....}`

What's going on?

**Comment by krabbypattified** [comment]
My use case isn't a canvas so I don't see why I should get a warning and `Matrix {d: NaN, a: NaN, f: NaN,.....}` for a negative `translateX` property

**Comment by epistemex** [comment]
`el` is an DOM element? If so, DOM elements aren't supported as argument. A matrix(-like) object must be passed in, or the matrix' individual values [a-f], or a vector.
