### ISSUE TITLE
Rotate with pivot

### ISSUE THREAD

**Issue by msageryd** [epistemex/transformation-matrix-js#5]
Thank you for this great library. I'll probably have great use of it, but I need to understand it a bit more.

Shouldn't I be able to rotate a polygon around a given pivot like this?

    const rotatedPolygon = new Matrix()
      .translate(-pivotX, -pivotY)
      .rotateDeg(45)
      .translate(pivotX, pivotY)
      .applyToArray(polygon);

`polygon`is an array of {x: , y: } objects

**Comment by epistemex** [comment]
The pivot translation needs to be the other way around, i.e. translate _to_ pivot, then rotate as rotation always happens around origin, and finally move back before applying:

```
const rotatedPolygon = new Matrix()
  .translate(pivotX, pivotY)      // translate to pivot and use as center
  .rotateDeg(45)                     // rotate around pivot/center
  .translate(-pivotX, -pivotY)   // translate back to corner 
  .applyToArray(polygon);
```

Example code: https://jsfiddle.net/ze2e7y0n/
